### PR TITLE
ports documentation to redoc

### PR DESCRIPTION
**Pull request by gewenyu99**
Draft for redoc proposal

### CODE REVIEW

**Comment by gewenyu99** [comment]
Moves use cases and examples further up. Talk is cheap, showing examples/uses cases earlier may be useful for readers.

Openapi specs are usually under openapi/openapi.yaml.

**Comment by gewenyu99** [comment]
The end result will look like this once github pages is setup. The content may be outdated in this link: https://gewenyu99.github.io/ga4gh-discovery-search/

**Review by jfuerth — APPROVED** [review]
Looks good to me, although the spec doc changes will conflict with PR #50 now.

**Comment by gewenyu99** [comment]
> Looks good to me, although the spec doc changes will conflict with PR #50 now.

I'll resolve these locally today.

**Comment by gewenyu99** [comment]
I'll manually merge these changes, then if it looks alright I'd like to merge this PR as soon as possible. The growing differences are not fun.

**Pull request merged**
