### PR TITLE
Proposed changes for release to PRC Friday 11/27

### PR DESCRIPTION
**Pull request by ianfore**
Am working on some changes to respond to PRC changes. Changes to Readme and Spec made. Working on final changes but started making commits so you can see what I'm working on. My final PR will come later if you can confirm this approach is workable.

### CODE REVIEW

**Comment by ianfore** [comment]
Made a second commit. Still not comfortable we've addressed the 'elevator speech' in the up-front material. The challenge comes from the fact this a low-level API with wide generality.

**Comment by ianfore** [comment]
Made what I am regarding as my final commit for this PR prior to 11/27 release to PRC.

**Review by jfuerth — APPROVED** [review]
This is a great improvement to the introductory text. Thank you!

+1 to merge.

**Comment by mcupak** [comment]
The PR overlaps with some changes already introduced in the release branch, we should cherry-pick the remaining changes and merge to `release-1.0.0` instead.

**Comment by mcupak** [comment]
This has now been cherry-picked to the release branch, thanks!

**Pull request closed without merging**
