### PR TITLE
Specify branch/tag used for git submodule

### LINKED ISSUE #85: Find a way to add a sidebar in Clyde
The current site does not state that its a GA4GH Search site clearly.

This is a theme issue, we'll need a custom feature added.

### LINKED ISSUE #90: Consolidate use cases in README
We have 2 sections - consolidate.

### LINKED ISSUE #91: Provide links to download clients in the docs

### PR DESCRIPTION
**Pull request by gewenyu99**
Fix #92 
Fix #85 <= this adds title to show it's search.

Fix #91 <= I added client installs to its own section under intro so its easier to find
Fix #90 <= @mcupak I think you wanted Applications and Use Cases to be combined. Let me know if this wasn't the case.

### CODE REVIEW

**Comment by gewenyu99** [comment]
A note about the submodules. The main repository(ga4gh-search) refers to a commit of the nested submodule repository. If we don't pull the submodule manually, then commit that change to the main repository, git will always try to update the submodule to the commit specified in the main repository. We don't have to worry about breaking Travis because the submodules have new commits upstream.

**Comment by mcupak** [comment]
Thanks @gewenyu99, looks good! A couple of comments/questions:
- The PR says if fixes #92, which is this PR. Was there a different issue number?
- Can you elaborate on what https://github.com/ga4gh-discovery/ga4gh-search/pull/92/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R15 does? Why do we need this?
- I added a clarification to #90 if we can adjust.
- In general, we should link commits to issues in commit messages, if you want to squash them and adjust (e.g. `issue #90`, `fix #90`).

**Comment by gewenyu99** [comment]
> * In general, we should link commits to issues in commit messages, if you want to squash them and adjust (e.g. `issue #90`, `fix #90`).

I've cleaned up my commits :P, hope that much easier to view. I will fix all my ugly commits before PRs next time :D 

> * The PR says if fixes #92, which is this PR. Was there a different issue number?
> * Can you elaborate on what https://github.com/ga4gh-discovery/ga4gh-search/pull/92/files#diff-

There is a branch v1.1.1 which will only get bug fixes. The file `.gitmodules` specifies the branch the submodule uses. When tracking branches in your submodules, `--remote` will allow the submodule to stay up to date with the branch specified.

> * I added a clarification to #90 if we can adjust. 

I will get this fixed

**Comment by mcupak** [comment]
Merged to `develop`.

**Pull request closed without merging**
