### PR TITLE
Replace covidcloud

### PR DESCRIPTION
**Pull request by shiroyuki**
This PR is to:
* replace all references to DNAstack's soon-to-be-decommissioned Data Connect services with data.publisher.dnastack.com;
* update all references to the tables accessible by the soon-to-be-decommissioned services to the tables with the new ones.

### CODE REVIEW

**Comment by jfuerth** [comment]
Thanks Juti. This looks good. Let's wait until the new endpoint at data.publisher.dnastack.com is functional so we can test these examples before merging.

**Comment by shiroyuki** [comment]
@jfuerth I think we can merge this now as `data.publisher.dnastack.com` is now functional.

By the way, I also update all table names with `public_` prefix. 😉

**Review by jfuerth — APPROVED** [review]
Looks good to me. Thanks for the updates!

**Comment by jfuerth** [comment]
@mcupak do we need a second approval before merging this?

**Pull request merged**
