### PR TITLE
Add REWS security clause to README, fix #64

### LINKED ISSUE #64: Add implementation security clause to the docs
From REWS product review:

`A stand-alone security review has been performed on the API. Nevertheless, any implementation that is linked to from the documentation accompanying the API is done so without any security guarantees. If you integrate this code into your application it is AT YOUR OWN RISK AND RESPONSIBILITY to arrange for an audit to ensure compliance with any applicable regulatory and security requirements, especially where personal data may be at issue.`

### PR DESCRIPTION
**Pull request by mcupak**

### CODE REVIEW

**Comment by rishidev** [comment]
If you want to link to the meeting minutes there is a permalink which will be up to date at https://w3id.org/ga4gh/minutes/discovery-search

**Comment by rishidev** [comment]
My email address will shortly become irrelevant so probably best to point users to https://www.ga4gh.org/contactus/

**Comment by rishidev** [comment]
The REWS text works well here. It might be good to duplicate in the documentation repository where we list the implementations as well.

**Comment by mcupak** [comment]
Thanks @rishidev, I updated the meeting minutes link and pointed the email to our Search group. We'll merge the docs repo into this one.

**Review by kemp-google — APPROVED** [review]

**Review by rishidev — APPROVED** [review]
LGTM

**Pull request merged**
